version: 0.2

phases:  
  install: 
    commands:
      - python -m pip install --upgrade pip
      - python -m pip install hatch
  build:
    commands:
      - python_path=`pyenv which python`
      - hatch_cmd=$(echo $python_path | sed "s/\(.*\)python/\1hatch/")
      - $hatch_cmd build -t wheel
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build artifacts are located in the dist directory

artifacts:
  files:
    - "**/*"
  base-directory: 'dist'