services:
  postgres:
    build: 
      context: .
      dockerfile: dockerfile-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./data:/var/lib/postgresql/data
    ports:
      - 5436:5432
