services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./data:/var/lib/postgresql/data
    ports:
      - 5436:5432
